USE LodeStarGameProductions;
GO
/*
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_ZipCode FOREIGN KEY(ZipCode) REFERENCES Zipcode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECk
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECk
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECk
ADD CONSTRAINT FK_ProductID FOREIGN KEY(ProductID) REFERENCES Products(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECk
ADD CONSTRAINT FK_ShippingID FOREIGN KEY(ShippingID) REFERENCES Shipping(ID)
ON UPDATE CASCADE
GO

ALTER TABLE Distributors WITH CHECK
ADD CONSTRAINT FK_Zip FOREIGN KEY(Zip) REFERENCES Zipcode(ZipCode)
ON UPDATE CASCADE
GO
*/
ALTER TABLE Shipping WITH CHECK
ADD CONSTRAINT FK_zipcodes FOREIGN KEY(zipcodes) REFERENCES Zipcode(ZipCode)
ON DELETE CASCADE
GO